name: Community CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate Repository Structure
        run: |
          required_files=("README.md" "LICENSE" "CONTRIBUTING.md")
          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "Missing required file: $file"
              exit 1
            fi
          done
      
      - name: Run Tests
        run: |
          if [ -f "./scripts/test.sh" ]; then
            chmod +x ./scripts/test.sh
            ./scripts/test.sh
          fi
